version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: guestbook
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
      - ./db_data:/usr/data
      - ./docker/mariadb/migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
